### ISSUE TITLE
Authenticator performance is erratic

### ISSUE THREAD

**Issue by JPL1** [maidsafe/beaker-plugin-safe-authenticator#137]
Operation System: Debian, Fedora
Beaker Version: 0.5.1

The Authenticator frequently does not log apps into the network. They fail with a 'could not connect to the network' message. This happens with the web hosting manager and the email app. It happens most often if other apps are open, but sometimes it happens at startup. App logfiles show bootstrapping and client whitelisting errors.

Workarounds include restarting everything, which sometimes works. More reliable is restarting the browser and revoking all permissions (including for the browser) then restarting the app. 

Other apps that often (usually) fail to authenticate are listy.test, and vidy.test. These should request authentication when the user uploads new content, but often this does not occur, or rather the request is not acknowledged (i.e. there is no popup asking for permission).

**Comment by bochaco** [comment]
Thanks @JPL1 , we were actively looking into https://maidsafe.atlassian.net/browse/MAID-2321 which I think it's the same issue you are reporting here, I'm not sure yet. We'll keep this updated.

**Comment by theWebalyst** [comment]
I have a similar problem with my own so, not Beaker, but it is not intermittent and so is blocking my development as I can't test any code. I'm not sure if it is the same issue, but posting here in case rather than kenning a new one.

I'm on Debian 8, using browser 0.5.1

Details in [this post](https://forum.safedev.org/t/baby-steps-problem-with-safeapp-connectauthorised/910?u=happybeing).

**Comment by theWebalyst** [comment]
In case it helps (possibly the same issue) I have some debug info here:
https://github.com/maidsafe/safe_browser/issues/162

**Comment by bochaco** [comment]
My understanding is that this was solved. I'm closing it now @JPL1 @theWebalyst but please feel free to re-open it if you still experience it on Alpha2 (just remember to consider the limit in the number of clients allowed as we discussed it on the forum).
