### ISSUE TITLE
Upload without Authenticator open.. ?expected behaviour

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/beaker-plugin-safe-authenticator#147]
So, I uploaded a site while the Authenticator was shutdown. Having previously been authenticated, the Web Hosting Manager appears to retain ability to upload. safe://testtest/ then exists where I expected it to fail.

Unclear to me whether that is intended behaviour, given previous tests that seemed not to be possible. I don't know, if the Authenticator then is just a bouncer now and not perpetually confirming access.

Prompts a thought about what control the Authenticator would have after granting access - would an app be able to ignore its revoking access, if the app doesn't need the Authenticator once it's got in?

**Comment by bochaco** [comment]
Hi @davidpbrown , unless I misunderstand the scenario, this is expected, the web hosting app receives the authorisation URI from the Authenticator and connects to the network with it. After that you can close the browser and the web hosting app should continue to wok without any issues.
However, if you decide to revoke the app from the Authenticator, the web hosting app should fail in any subsequent operation attempt, forcing the app to authorise itself again and connect again with a new authorisation URI.
