### ISSUE TITLE
‘Unable to revoke app’ error

### ISSUE THREAD

**Issue by JPL1** [maidsafe/beaker-plugin-safe-authenticator#151]
I am now unable to revoke any apps.  
![error21oct](https://user-images.githubusercontent.com/12783198/31864596-3a865dea-b760-11e7-8dbf-2b5e46ee8ebd.png)

Closing the browser and restarting does not cure the problem.

**Comment by nbaksalyar** [comment]
@JPL1 thanks for your report!
Can you please share your log file for our further investigation?
It should be `authenticator.log` in the browser working directory.

**Comment by JPL1** [comment]
Hi @nbaksalyar 
Please see attached. I'm in Windows 10 by the way, using the installed SAFE Browser.

By the way the safe_browser.log has this message:
SAFE_Browser.MaidSafe.log:

D 17-10-23 16:33:19.058889 [safe_app::ffi::ipc ipc.rs:169] **ERRNO: -2000** Unexpected("Couldn\'t authenticate app that is pending revocation")

[authenticator-log.txt](https://github.com/maidsafe/beaker-plugin-safe-authenticator/files/1407751/authenticator-log.txt)

**Comment by nbaksalyar** [comment]
@JPL1, thank you for providing the log file!

We have created a tracking issue in [JIRA](https://maidsafe.atlassian.net/browse/MAID-2407) and we'll try to find out how to debug this.

**Comment by JPL1** [comment]
I thing this has something to do with safe://chaty.

To reproduce: 
Open safe://chaty and agree to default authenticator permissions
Send a message - agree to default authenticator permissions
Try to revoke chaty.
After the authenticator fails to revoke chaty, it will fail to revoke all susequent apps too

**Comment by nbaksalyar** [comment]
Fixed via #608.
@JPL1, thank you for the detailed reports! It helped a lot. :)
