### ISSUE TITLE
Authentication Error burns up allocated instances

### ISSUE THREAD

**Issue by tomcarlson** [maidsafe/beaker-plugin-safe-authenticator#98]
We are allowed 4 instances (what's the correct word here?)   4 apps can connect to the SAFE Network.

However, if you fail to authenticate because you mistyped username/password, after you do successfully authenticate, you won't be able to get another app to communicate on SAFE.  The act of attempting a login that fails, will doom your apps to non-communication until you restart the SAFE browser

To duplicate.

1. Restart the SAFE browser to start with a clean slate
2. Authenticate, but purposely mistype username or password so you get authentication error
3. Correct your username or password and go ahead and login
4. Go to  safe://app.portlandspirit and watch it fail to read mutable data
5. Restart the SAFE browser to start with a clean slate
6. Carefully type username/password so you authenticate successfully the 1st time
7. Go to safe://app.portlandspirit  and watch it succeed in reading mutable data
8. Repeat as necessary to convince yourself that this is because of the 1st failed authentication

**Comment by shankar2105** [comment]
Hi @tomcarlson, thanks for your support, we will try to reproduce the issue. Could be helpful for us if you share some more information like the platform, arch, etc. on which you tried.

**Comment by bochaco** [comment]
This is still not reproducible with latest versions. I'm closing it now. @tomcarlson please feel free to reopen it if you still experience this same behaviour in our next release.
